---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_connection: docker
      ansible_user: root

vector:
  hosts:
    vector-01:
      ansible_connection: docker
      ansible_user: root

lighthouse:
  hosts:
    lighthouse-01:
      ansible_connection: docker
      ansible_user: root
