---
all:
  hosts:
    jenkins-master-01:
      ansible_host: 84.252.143.46
    jenkins-agent-01:
      ansible_host: 84.252.142.236
  children:
    jenkins:
      children:
        jenkins_masters:
          hosts:
            jenkins-master-01:
        jenkins_agents:
          hosts:
              jenkins-agent-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: psi