version: "3.9"
services:
  elasticsearch:
    image: "centos:centos7"
    container_name: elasticsearch
    tty: true
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk

  kibana:
    image: "centos:centos7"
    container_name: kibana
    tty: true
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  logstash:
    image: "centos:centos7"
    container_name: logstash
    tty: true
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge