#Не работает docker-compose, прав не хватает на systemctl
version: "3.9"
services:
  clickhouse-01:
    image: "centos:7"
    container_name: clickhouse-01
    tty: true
#    ports:
#      - "9000:9000"
#      - "8123:8123"
#      - "9009:9009"
    privileged: true

  vector-01:
    image: "centos:7"
    container_name: vector-01
    tty: true

#docker run -d -it --privileged --network=my-net --name=vector-01 centos:7 /usr/sbin/init
#docker run -d -it --privileged -p 8123:8123 -p 9000:9000 -h 127.0.0.1 --network=my-net --name=clickhouse-01 centos:7 /usr/sbin/init
#docker run -d -it --privileged -p 80:80 --network=my-net --name=lighthouse-01 centos:7 /usr/sbin/init