filebeat.inputs:
  - type: container
    paths:
      - '/var/lib/docker/containers/*/*.log'

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"

  - decode_json_fields:
      fields: ["message"]
      target: "json"
      overwrite_keys: true

output.logstash:
  hosts: ["logstash:5044"]
  # indices:
  #   - index: "logstash-%{[agent.version]}-%{+yyyy.MM.dd}"

# output.elasticsearch:
#  hosts: ["es-hot:9200"]
#  indices:
#    - index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"

#output.console:
#  enabled: true

logging.json: true
logging.metrics.enabled: false
